- name: generate grub
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: restart chrony
  systemd:
    name: chronyd
    state: restarted

- name: restart postfix
  systemd:
    name: postfix
    state: restarted

- name: reload auditd
  shell: service auditd reload

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
