- name: generate grub
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: restart chrony
  systemd:
    name: chronyd
    state: restarted

- name: restart postfix
  systemd:
    name: postfix
    state: restarted

- name: restart auditd
  service:
    name: auditd
    state: restarted

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
