- name: remove firewalld
  yum:
    name: firewalld
    state: absnet

- name: Installe iptables packages
  yum:
    name: ["iptables", "iptables-services"]
    state: installed

- name: Block that triggers iptables actions
  block:
    - name: flush the tables
      iptables:
        chain: "{{ item }}"
        flush: yes
      with_items:
        - INPUT
        - FORWARD
        - OUTPUT

    - name: allow in on lo
      iptables:
        chain: INPUT
        jump: ACCEPT
        in_interface: lo

    - name: allow out on lo
      iptables:
        chain: OUTPUT
        jump: ACCEPT
        out_interface: lo

    - name: block 127.0.0.0/8 on INPUT
      iptables:
        chain: INPUT
        jump: DROP
        source: 127.0.0.1/8

    - name: Allow established and related
      iptables:
        chain: "{{ item }}"
        jump: ACCEPT
        ctstate: ESTABLISHED,RELATED
      with_items:
        - INPUT
        - OUTPUT

    - name: Allow inbound ssh
      iptables:
        chain: INPUT
        jump: ACCEPT
        ctstate: NEW
        protocol: tcp
        syn: match
        destination_port: 22

    - name: Set default policy for the chains
      iptables:
        chain: "{{ item }}"
        policy: DROP
      with_items:
        - INPUT
        - FORWARD
        - OUTPUT
  when: iptables_initial
  notify: save iptables rules

- name: Make sure iptables is started and enabled
  systemd:
    name: iptables
    state: started
    enabled: true
