- name: Get correct playbooks based on os + version
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - default.yml
