- name: Copy auditd.conf
  template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: 0640
  notify: reload auditd

- name: Ensure auditing for processes that start prior to auditd is enabled
  lineinfile:
    path: /etc/default/grub
    backrefs: yes
    regexp: '^GRUB_CMDLINE_LINUX="(.*) audit=1"$'
    line: 'GRUB_CMDLINE_LINUX="\1 audit=1"'
  notify: generate grub

- name: Add auditd rules
  template:
    src: cis.rules.j2
    dest: /etc/audit/rules.d/CIS.rules
    owner: root
    group: root
    mode: 0640
  notify: reload auditd

- name: Copy rsyslog.conf
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog

- name: Ensure permissions on all logfiles are configured
  shell: "find /var/log -type f -exec chmod g-wx,o-rwx {} +"
  register: logfile_permissions
  changed_when: logfile_permissions.stdout != ""
