- name: Remove packages
  yum:
    name: "{{ remove_packages }}"
    state: absent

- name: Add packages
  yum:
    name: "{{ add_packages }}"
    state: present

- name: Add all the latesr security packages
  yum:
    name: "*"
    state: latest
    security: yes
