modprobe_filesystems:
  - cramfs
  - freevxfs
  - jffs2
  - hfs
  - hfsplus
  - squashfs
  - udf
  - vfat
modprobe_network:
  - dccp
  - sctp
  - rds
  - tipc
required_partitions:
  - /home
  - /var
  - /var/log
  - /var/log/audit
  - /tmp
#The password should be removed and added to a vault (as below) or vars_prompt used
#grub2_password: {{ vault_grub2_password }}
grub2_password: changeme
motd_message: "Temporary MOTD"
issue_message: "Authorized uses only. All activity will be monitored and reported."
iptables_modify: true
#rsyslog_forward:
#  - logs: "*.*"
#    protocol: "tcp"
#    ip: "192.168.122.24"
#    port: "514"
pwquality_minlen: "14"
pwquality_dcredit: "-1"
pwquality_ucredit: "-1"
pwquality_ocredit: "-1"
pwquality_lcredit: "-1"
pam_auth_options: "audit deny=5 unlock_time=900"
#pam_pwhistory: true
#password_max_age: 365
#password_min_days: 7
#password_warning_age: 7
password_lock_days: 90
run_slow_tasks: true
