disable_systemd:
  - autofs
  - chargen-dgram
  - chargen-stream
  - daytime-dgram
  - daytime-stream
  - discard-dgram
  - discard-stream
  - echo-dgram
  - echo-stream
  - time-dgram
  - time-stream
  - tftp
  - xinetd
  - avahi-daemon
  - cups
  - dhcpd
  - slapd
  - nfs
  - nfs-server
  - rpcbind
  - named
  - vsftpd
  - httpd
  - dovecot
  - smb
  - squid
  - snmpd
  - ypserv
  - rsh.socket
  - rlogin.socket
  - rexec.socket
  - telnet.socket
  - tfpt.socket
  - rsyncd
  - ntalk
enable_systemd:
  - auditd
  - rsyslog
  - crond
